// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Posts.API.Data;

#nullable disable

namespace Posts.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240711054451_initialDatabase")]
    partial class initialDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Posts.API.Models.Domain.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Hello, I This is not acceptable.",
                            DateTime = new DateTime(2024, 7, 11, 5, 44, 50, 749, DateTimeKind.Utc).AddTicks(7506),
                            Publisher = "Tom"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Hey, tell your borthoer to bring the umbrella with him.",
                            DateTime = new DateTime(2024, 7, 11, 5, 44, 50, 749, DateTimeKind.Utc).AddTicks(7550),
                            Publisher = "Sam"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
